<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\building-blocks\Crm.BuildingBlocks\Crm.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\contracts\csharp\Crm.Contracts\Crm.Contracts.csproj" />
  </ItemGroup>
</Project>
